### ISSUE TITLE
OverflowError + The generated URLs do not work :(

### ISSUE THREAD

**Issue by aes512** [narenaryan/Pyster#4]
I'm getting OverflowErrors and the URLs this generates do not work at all. Here are the errors:

- https://bpaste.net/show/75071b041981

My environment:

- OSX
- Python 2.7.13
- Using supplied requirements.txt in a virtualenv 
- master branch (c5c0abe22ab6dfdad95eee312f4d7692810c81b6)

Any ideas?

**Comment by mathana96** [comment]
Hi @aes512, I am facing the same issue. 

I changed `INT` to `INTEGER` here; 

```python
def table_check():
    create_table = """
        CREATE TABLE WEB_URL(
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        URL TEXT NOT NULL
        );
        """
    with sqlite3.connect('urls.db') as conn:
        cursor = conn.cursor()
        try:
          cursor.execute(create_table)
        except OperationalError:
            pass
```

I changed because I got the error `OperationalError: no such table: WEB_URL`. 

When I removed the error catching mechanism from the snippet above, it said `OperationalError: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY`. 

Changing to `INTEGER` allows it to run, but end up with `OverflowError: Python int too large to convert to SQLite INTEGER`

Hope you are able to throw some light on this @narenaryan 😄

**Comment by mathana96** [comment]
It works when you input with `https://`, for example, `https://www.google.com`
🤔

**Comment by scheung38** [comment]
Same thing for me too. But somehow a shortened URL is able to be generated? 

Within the redirect_short_url function, should 

             cursor = conn.cursor()
             res = cursor.execute('SELECT URL FROM WEB_URL WHERE ID=?', [decoded])

these two lines of code not go into the try block?

**Comment by jeffmcneill** [comment]
Is this still a stopping bug? Does the app not work at this point?

**Comment by HarveyHunt** [comment]
The overflow error isn't a stopping bug, the application still works after it.

When a web browser connects to the site it requests ```/favicon.ico```, which ```Pyster``` interprets as a shortened URL and tries to look it up in the DB. However when converting the string to base 10 it creates a number so large that it overflows the ```sqlite``` max int size.

```python
>>> main.toBase10('favicon.ico')
12731693989753484736

# sqlite3 Max int size
>>> 9223372036854775807 > 12731693989753484736
False
```

A quick fix would be for ```redirect_short_url``` to check that the ```short_url``` isn't ```'favicon.ico'```

**Comment by HarveyHunt** [comment]
An ```OverflowError``` also occurs when running with Python 3 and passing in a URL that is missing ```http://```.  ```home()``` checks to see if the URL scheme is an empty string, but it is actually an empty bytes object:

```python
>>> '' == b''
False
```

This means that the ```http://``` prefix is never added to the URL before it being stored in the DB. This means that ```redirect()``` redirects to "http://localhost:5000/my_url" rather than "http://my_url", causing a short url lookup which results in an ```OverflowError```.

**Comment by ab-anand** [comment]
@scheung38 The insertion of a new record is never committed in the DB which causes this problem.
Fixed it by adding one line `conn.commit()`
Check my PR for more details.

**Comment by ab-anand** [comment]
@narenaryan You can close this issue now :)

**Comment by narenaryan** [comment]
I merged @ab-anand PR. Thanks for everyone for pointing those issues.
